title: My Notes
description: Study and tech notes
url: "https://gsg27.github.io"
theme: minima

minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
